@extends('layouts.app')
@section('title', 'Manage '.$listing->name.' | Marketing Bidding Central')
@section('robots', 'noindex, nofollow')
@section('content')
@include('admin._header', ['eyebrow' => 'Listing management', 'title' => $listing->name, 'description' => $listing->category->name.' · '.ucfirst($listing->status).' · '.$listing->normalized_url])
<section class="admin-page"><div class="admin-listing-summary"><div><span>Current total</span><strong>{{ $listing->formattedBid() }}</strong></div><div><span>Confirmed Stripe payments</span><strong>${{ number_format($realPaidCents / 100, 2) }}</strong></div><div><span>Listing views</span><strong>{{ number_format($listing->impression_count) }}</strong></div><div><span>Link clicks</span><strong>{{ number_format($listing->click_count) }}</strong></div><a class="button secondary" href="{{ route('home', ['listing' => $listing->slug]) }}#listing-view">View public listing</a></div>
<div class="admin-detail-grid"><article class="admin-card"><p class="kicker">Public information</p><h2>Edit listing</h2><form class="admin-form" method="post" action="{{ route('admin.listings.update', $listing) }}">@csrf<div class="field-grid"><label>Name<input name="name" value="{{ $listing->name }}" required></label><label>URL<input name="url" value="{{ $listing->normalized_url }}" required></label></div><div class="field-grid"><label>Category<select name="category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected($listing->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Status<select name="status">@foreach(['pending','active','rejected','suspended','banned'] as $status)<option value="{{ $status }}" @selected($listing->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label></div><label>Short description<input name="short_description" value="{{ $listing->short_description }}" maxlength="240" required></label><label>Full description<textarea name="description" maxlength="4000">{{ $listing->description }}</textarea></label><label>Audit reason<input name="reason" placeholder="Why are you changing it?" required></label><button class="button primary">Save listing</button></form></article>
<aside class="admin-card"><p class="kicker">Owner action</p><h2>Adjust total</h2><p>This adds an auditable ledger entry. It does not create or imitate a Stripe payment.</p><form class="admin-form" method="post" action="{{ route('admin.listings.adjust', $listing) }}">@csrf<label>Direction<select name="direction"><option value="add">Add to total</option><option value="subtract">Subtract from total</option></select></label><label>Amount ($)<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Reason<textarea name="reason" required></textarea></label><button class="button secondary">Record adjustment</button></form></aside></div>
<article class="admin-card admin-section"><div class="admin-card-head"><div><p class="kicker">Money and rank</p><h2>Payment and adjustment log</h2></div><span>{{ $bids->total() }} entries</span></div><div class="table-wrap"><table><thead><tr><th>When</th><th>Type</th><th>Change</th><th>Previous</th><th>New total</th><th>Status</th><th>Transaction</th></tr></thead><tbody>@foreach($bids as $bid)<tr><td>{{ $bid->created_at->format('M j, Y g:i A') }}</td><td>{{ str_replace('_', ' ', ucfirst($bid->payment_provider)) }}</td><td>{{ $bid->signed_delta_cents >= 0 ? '+' : '-' }}${{ number_format(abs($bid->signed_delta_cents) / 100, 2) }}</td><td>${{ number_format($bid->previous_total_cents / 100, 2) }}</td><td><strong>${{ number_format($bid->new_total_cents / 100, 2) }}</strong></td><td>{{ ucfirst($bid->payment_status) }}</td><td>@if($bid->transaction)<span>{{ ucfirst($bid->transaction->status) }} · {{ $bid->transaction->provider }}</span>@else<span class="muted">No payment transaction</span>@endif @if($bid->notes)<small>{{ $bid->notes }}</small>@endif</td></tr>@endforeach</tbody></table></div>{{ $bids->links() }}</article>
<div class="admin-detail-grid"><article class="admin-card"><p class="kicker">Traffic</p><h2>Last 30 metric days</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Views</th><th>Clicks</th><th>Filtered</th></tr></thead><tbody>@foreach($listing->metrics as $metric)<tr><td>{{ $metric->metric_date->format('M j, Y') }}</td><td>{{ $metric->impressions }}</td><td>{{ $metric->clicks }}</td><td>{{ $metric->bot_filtered }}</td></tr>@endforeach</tbody></table></div></article><article class="admin-card"><p class="kicker">Moderation</p><h2>Reports</h2>@forelse($reports as $report)<div class="admin-report"><strong>{{ ucfirst($report->reason) }}</strong><span>{{ ucfirst($report->status) }} · {{ $report->created_at->format('M j, Y') }}</span><p>{{ $report->details ?: 'No additional details.' }}</p></div>@empty<p>No reports for this listing.</p>@endforelse</article></div></section>
@endsection
